[package]
description = "Durian"
name = "durian"
version = "0.1.0"
authors = ["Mostafa Sedaghat Joo <mostafa.sedaghat@gmail.com>"]

[dependencies]
byteorder = "1.0"
ethereum-types = "0.8.0"
parity-bytes = "0.1"
rocket = "0.4.2"
rocket_codegen = "0.4.2"
serde_derive = "1.0.104"
rocket_contrib_codegen = "0.4.2"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dependencies.ethcore-miner]
git = "https://github.com/b00f/parity-ethereum.git"

[dependencies.vm]
git = "https://github.com/b00f/parity-ethereum.git"

[dependencies.machine]
git = "https://github.com/b00f/parity-ethereum.git"

[dependencies.trace]
git = "https://github.com/b00f/parity-ethereum.git"

[dependencies.wasm]
git = "https://github.com/b00f/parity-ethereum.git"

[dependencies.common-types]
git = "https://github.com/b00f/parity-ethereum.git"

[lib]
path = "src/lib.rs"
