[package]
name = "cli"
version = "0.1.0"
authors = ["Mostafa <mostafa.sedaghat@gmail.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.8.0"
serde_derive = "1.0.103"
bincode = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.8.2"
durian = { path = ".." }
simple_logger = "1.4.0"
log = "0.4"
jsonrpc-client-core = "0.5.0"
jsonrpc_client = "0.2.0"
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-http-server = "14.0.5"
jsonrpc-tcp-server = "14.0.5"
jsonrpc-ws-server = "14.0.5"
jsonrpc-stdio-server = "14.0.5"
jsonrpc-derive = "14.0.5"
jsonrpc-server-utils = "14.0.5"
jsonrpc-pubsub = "14.0.5"
serde_json = { version = "1.0", features = ["arbitrary_precision"]}



[features]
arbitrary_precision = ["serde_json/arbitrary_precision"]