[package]
name = "cli"
version = "0.1.0"
authors = ["Mostafa <mostafa.sedaghat@gmail.com>"]
edition = "2018"


[dependencies]
ethereum-types = "0.8.0"
bincode = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.8.2"
durian = { path = ".." }
rpc-durian = { path = "../http" }
simple_logger = "1.4.0"
log = "0.4"
serde_json = { version = "1.0", features = ["arbitrary_precision"]}
serde_derive = "1.0.104"
chrono = { version = "0.3", features = ["serde"] }
rustc-hex = "1.0"
tonic = "0.1"
prost = "0.6"
jsonrpc-core = "14.0.5"
jsonrpc-http-server = "14.0.5"
jsonrpc-server-utils = "14.0.5"

[build-dependencies]
tonic-build = "0.1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[features]
arbitrary_precision = ["serde_json/arbitrary_precision"]