[package]
name = "cli"
version = "0.1.0"
authors = ["Mostafa <mostafa.sedaghat@gmail.com>"]
edition = "2018"


[[bin]] # Bin to run the HelloWorld gRPC server
name = "contract-server"
path = "src/service.rs"

# [[bin]] # Bin to run the HelloWorld gRPC server
# name = "helloworld-client"
# path = "src/client.rs"


[dependencies]
ethereum-types = "0.8.0"
bincode = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.8.2"
durian = { path = ".." }
simple_logger = "1.4.0"
log = "0.4"
serde_json = { version = "1.0", features = ["arbitrary_precision"]}
serde_derive = "1.0.104"
rocket = "0.4.2"
rocket_codegen = "0.4.2"
rocket_contrib_codegen = "0.4.2"
chrono = { version = "0.3", features = ["serde"] }
jsonrpc-core = "14.0.5"
jsonrpc-http-server = "14.0.5"
rustc-hex = "1.0"
jsonrpc-derive = "14.0.3"
jsonrpc-ws-server = "14.0.3"
jsonrpc-ipc-server = "14.0.3"
jsonrpc-pubsub = "14.0.3"
jsonrpc-client-core = "0.5.0"
tonic = "0.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
actix-web = "2.0.0"

[build-dependencies]
tonic-build = "0.1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[features]
arbitrary_precision = ["serde_json/arbitrary_precision"]